{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# View and Frontend Coding\n",
    "> Frontend coding and backend design will always be related.  In building Views you we will need to create in frontend designs that will work with the backend data or databases. \n",
    "\n",
    "- title: View and Frontend Coding\n",
    "- toc: true\n",
    "- categories: []\n",
    "- image: /images/javascript.png\n",
    "- type: pbl\n",
    "- week: 18"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## GitHub Pages Organization and Design\n",
    "> HTML, JavaScript, and a JavaScript fetch are all things you can do in a GitHub Pages View.  Additionally, every GitHub page inherits from Theme, minimizing need to define a lot of CSS.  Some key elements...\n",
    "- Style, the visual design.\n",
    "    - SASS files in `assets/css/style.scss`, review GitHub pages theme for instructions\n",
    "- Head and Body.  The HTML tags used to structure every page.\n",
    "    - Layout files in `_layouts/default.html`, structure is provided by GitHub pages theme\n",
    "    - Supplement layout with files in `_includes`, for instance `_layouts/home.html` is used to add menu selections to pages by including it in `_layouts/default.html`.\n",
    "- Page. Markdown or HTML is defined and constructed into page using Jekyll Build, refer to `content` reference in `_layouts/default.html`.  Observe how files are built by looking at generated `html` files under `_site`."
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## View/CRUD Concepts\n",
    "> In a database project, the key idea is to build a system for capturing key information.   For instance, ***student information*** on students and allowing ***blogging** to a Teacher would have Frontend View elements that correspond to a Backend Database.  \n",
    "\n",
    "> Backend Database CRUD operations are as follows...\n",
    "- Create new student records\n",
    "- Read a list of students\n",
    "- Update student data\n",
    "- Delete records\n",
    "\n",
    "### Frontend Visual concepts of the Idea\n",
    "![Screen Concept](images/crud.png)\n",
    "\n",
    "### HTML to Obtain Input is a key step (aka Create/Input Step)\n",
    "\n",
    "#### HTML5 table is a way to organize input\n",
    "- th labels\n",
    "- td input types\n",
    "- onclick action"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "/*\n",
    "<table>\n",
    "    <tr>\n",
    "        <th><label for=\"name\">Name</label></th>\n",
    "        <th><label for=\"email\">Email</label></th>\n",
    "        <th><label for=\"password\">Password</label></th>\n",
    "        <th><label for=\"phone\">Phone</label></th>\n",
    "    </tr>\n",
    "    <tr>\n",
    "        <td><input type=\"text\" name=\"name\" id=\"name\" required></td>\n",
    "        <td><input type=\"email\" name=\"email\" id=\"email\" placeholder=\"abc@xyz.org\" required></td>\n",
    "        <td><input type=\"password\" name=\"password\" id=\"password\" required></td>\n",
    "        <td><input type=\"tel\" name=\"phone_num\" id=\"phone_num\"\n",
    "            pattern=\"[0-9]{3}-[0-9]{3}-[0-9]{4}\"\n",
    "            placeholder=\"999-999-9999\"></td>\n",
    "        <td ><button onclick=\"create_User()\">Create</button></td>\n",
    "    </tr>\n",
    "</table>\n",
    "*/"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Table</h3>\n",
    "<table>\n",
    "    <tr>\n",
    "        <th><label for=\"name\">Name</label></th>\n",
    "        <th><label for=\"email\">Email</label></th>\n",
    "        <th><label for=\"password\">Password</label></th>\n",
    "        <th><label for=\"phone\">Phone</label></th>\n",
    "    </tr>\n",
    "    <tr>\n",
    "        <td><input type=\"text\" name=\"name\" id=\"name\" required></td>\n",
    "        <td><input type=\"email\" name=\"email\" id=\"email\" placeholder=\"abc@xyz.org\" required></td>\n",
    "        <td><input type=\"password\" name=\"password\" id=\"password\" required></td>\n",
    "        <td><input type=\"tel\" name=\"phone_num\" id=\"phone_num\"\n",
    "            pattern=\"[0-9]{3}-[0-9]{3}-[0-9]{4}\"\n",
    "            placeholder=\"999-999-9999\"></td>\n",
    "        <td ><button onclick=\"create_User()\">Create</button></td>\n",
    "    </tr>\n",
    "</table>"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "#### HTML5 form is another way to organize input\n",
    "- form action vs onclick\n",
    "- p labels and input, in real implementation combine with CSS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "/*\n",
    "<form action=\"create_User()\">\n",
    "    <p><label>\n",
    "        Name:\n",
    "        <input type=\"text\" name=\"name\" id=\"name\" required>\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        User ID:\n",
    "        <input type=\"text\" name=\"uid\" id=\"uid\" required>\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        Password:\n",
    "        <input type=\"password\" name=\"password\" id=\"password\" required>\n",
    "        Verify Password:\n",
    "        <input type=\"password\" name=\"passwordV\" id=\"passwordV\" required>\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        Phone:\n",
    "        <input type=\"tel\" name=\"phone_num\" id=\"phone_num\"\n",
    "            pattern=\"[0-9]{3}-[0-9]{3}-[0-9]{4}\"\n",
    "            placeholder=\"999-999-9999\">\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        Birthday:\n",
    "        <input type=\"date\" name=\"dob\" id=\"dob\">\n",
    "    </label></p>\n",
    "    <p>\n",
    "        <button>Create</button>\n",
    "    </p>\n",
    "</form>\n",
    "*/"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<h3>Form</h3>\n",
    "<form>\n",
    "    <p><label>\n",
    "        Name:\n",
    "        <input type=\"text\" name=\"name\" id=\"name\" required>\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        User ID:\n",
    "        <input type=\"text\" name=\"uid\" id=\"uid\" required>\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        Password:\n",
    "        <input type=\"password\" name=\"password\" id=\"password\" required>\n",
    "        Verify Password:\n",
    "        <input type=\"password\" name=\"passwordV\" id=\"passwordV\" required>\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        Phone:\n",
    "        <input type=\"tel\" name=\"phone_num\" id=\"phone_num\"\n",
    "            pattern=\"[0-9]{3}-[0-9]{3}-[0-9]{4}\"\n",
    "            placeholder=\"999-999-9999\">\n",
    "    </label></p>\n",
    "    <p><label>\n",
    "        Birthday:\n",
    "        <input type=\"date\" name=\"dob\" id=\"dob\">\n",
    "    </label></p>\n",
    "    <p>\n",
    "        <button>Create</button>\n",
    "    </p>\n",
    "</form>"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### JavaScript Fetch and Response (aka Post Step)\n",
    "- After Input call action\n",
    "- Extract data from DOM\n",
    "- Build url\n",
    "- Fetch\n",
    "- Add response to end of table"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "function create_User(){\n",
    "    // extract data from inputs\n",
    "    const name = document.getElementById(\"name\").value;\n",
    "    const email = document.getElementById(\"email\").value;\n",
    "    const password = document.getElementById(\"password\").value;\n",
    "    const phone = document.getElementById(\"phone\").value;\n",
    "    const requestOptions = {\n",
    "        method: 'POST',\n",
    "        headers: {\n",
    "            'Content-Type': 'application/json',\n",
    "            'Authorization': 'Bearer my-token',\n",
    "        },\n",
    "    };\n",
    "    //url for Create API\n",
    "    const url='/crud_api/create/' + name + '/' + email+ '/' + password + '/' + phone;\n",
    "    //Async fetch API call to the database to create a new user\n",
    "    fetch(url, requestOptions).then(response => {\n",
    "        // prepare HTML search result container for new output\n",
    "        const resultContainer = document.getElementById(\"result\");\n",
    "        // trap error response from Web API\n",
    "        if (response.status !== 200) {\n",
    "            const errorMsg = 'Database response error: ' + response.status;\n",
    "            console.log(errorMsg);\n",
    "            // Email must be unique, no duplicates allowed\n",
    "            document.getElementById(\"pswError\").innerHTML =\n",
    "                \"Email already exists in the table\";\n",
    "            return;\n",
    "        }\n",
    "        // response contains valid result\n",
    "        response.json().then(data => {\n",
    "            console.log(data);\n",
    "            //add a table row for the new/created userId\n",
    "            const tr = document.createElement(\"tr\");\n",
    "            for (let key in data) {\n",
    "                if (key !== 'query') {\n",
    "                    //create a DOM element for the data(cells) in table rows\n",
    "                    const td = document.createElement(\"td\");\n",
    "                    console.log(data[key]);\n",
    "                    //truncate the displayed password to length 20\n",
    "                    if (key === 'password'){\n",
    "                        td.innerHTML = data[key].substring(0,17)+\"...\";\n",
    "                    }\n",
    "                    else{\n",
    "                        td.innerHTML = data[key];}\n",
    "                    //add the DOM data element to the row\n",
    "                    tr.appendChild(td);\n",
    "                }\n",
    "            }\n",
    "            //append the DOM row to the table\n",
    "            table.appendChild(tr);\n",
    "        })\n",
    "    })\n",
    "}"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### HTML and JavaScript Display Table\n",
    "> JavaScript below shows elements needed to construct the rows of data in the table.\n",
    "- JSON is required, it is hardcoded in this example.  Typically JSON will come from a JavaScript fetch.\n",
    "- JSON object is required, it is created from JSON string.  This allows access to to elements in JSON using JavaScript dot notation (user._name)\n",
    "- DOM editing is a huge part of the remainder of this example.  DOM elements often nest inside of other DOM elements.   For instance each `td`  is nested in `tr`.  ***Find examples*** of DOM create and append in the code below.\n",
    "- Notice the definition of ***table*** and build you own map or visual of how these things are put together."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "/*\n",
    "<table>\n",
    "  <thead>\n",
    "  <tr>\n",
    "    <th>Name</th>\n",
    "    <th>ID</th>\n",
    "    <th>Actions</th>\n",
    "  </tr>\n",
    "  </thead>\n",
    "  <tbody id=\"table\">\n",
    "    <!-- javascript generated data -->\n",
    "  </tbody>\n",
    "</table>\n",
    "*/\n",
    "\n",
    "// Static json, this can be used to test data prior to API and Model being ready\n",
    "const json = '[{\"_name\": \"Thomas Edison\", \"_uid\": \"toby\"}, {\"_name\": \"Nicholas Tesla\", \"_uid\": \"nick\"}, {\"_name\": \"John Mortensen\", \"_uid\": \"jm1021\"}, {\"_name\": \"Eli Whitney\", \"_uid\": \"eli\"}, {\"_name\": \"Hedy Lemarr\", \"_uid\": \"hedy\"}]';\n",
    "\n",
    "// Convert JSON string to JSON object\n",
    "const data = JSON.parse(json);\n",
    "\n",
    "// prepare HTML result container for new output\n",
    "const table = document.getElementById(\"table\");\n",
    "data.forEach(user => {\n",
    "    // build a row for each user\n",
    "    const tr = document.createElement(\"tr\");\n",
    "\n",
    "    // td's to build out each column of data\n",
    "    const name = document.createElement(\"td\");\n",
    "    const id = document.createElement(\"td\");\n",
    "    const action = document.createElement(\"td\");\n",
    "           \n",
    "    // add content from user data          \n",
    "    name.innerHTML = user._name; \n",
    "    id.innerHTML = user._uid; \n",
    "\n",
    "    // add action for update button\n",
    "    var updateBtn = document.createElement('input');\n",
    "    updateBtn.type = \"button\";\n",
    "    updateBtn.className = \"button\";\n",
    "    updateBtn.value = \"Update\";\n",
    "    updateBtn.style = \"margin-right:16px\";\n",
    "    updateBtn.onclick = function () {\n",
    "      alert(\"Update: \" + user._uid);\n",
    "    };\n",
    "    action.appendChild(updateBtn);\n",
    "\n",
    "    // add action for delete button\n",
    "    var deleteBtn = document.createElement('input');\n",
    "    deleteBtn.type = \"button\";\n",
    "    deleteBtn.className = \"button\";\n",
    "    deleteBtn.value = \"Delete\";\n",
    "    deleteBtn.style = \"margin-right:16px\"\n",
    "    deleteBtn.onclick = function () {\n",
    "      alert(\"Delete: \" + user._uid);\n",
    "    };\n",
    "    action.appendChild(deleteBtn);  \n",
    "\n",
    "    // add data to row\n",
    "    tr.appendChild(name);\n",
    "    tr.appendChild(id);\n",
    "    tr.appendChild(action);\n",
    "\n",
    "    // add row to table\n",
    "    table.appendChild(tr);\n",
    "});"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## View/Blog Concepts\n",
    "> A notes/blog would be created to add ***Notes*** between students and teacher, part of original concept.  Notes could be used for many types of applications. Details on creating notes will be part of another blog, but for now we want you to think about design.\n",
    "- In this design, most recent messages are on top\n",
    "- Messages are intended to support markdown and inclusion of images\n",
    "- Think about technique to format images in conjunction with Text\n",
    "\n",
    "![Notes and Images](images/notes.png)\n"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Hacks\n",
    "> Build and correlate a technical design between frontend view and backend model.  This blog is focussing on frontend view., and visual concepts on how CRUD operations are presented to user of system. This particular Jupyter Notebook and code within it are used to help establish technical ideas.   Start a design for your project...\n",
    "- Each project must have  a View (as pictured) and Model (json data is fetched into the View).  Describe your project.\n",
    "- Describe your View.  Use Markdown, HTML, ***UML***, other visuals, tables are used to characterize a project.  This shows the Teacher and Graders understanding of planning Model and View.\n",
    "- Transition from pure design and start inserting code elements, like inputs.  Also,  try build a table with json data versus fetching data.\n",
    "- Issues should discuss problems/challenges, in Teacher/Student data here are a couple ... \n",
    "    - This design will have many JavaScript actions, at least one for each CRUD operation.  In this design, developer needs think of JavaScript functions to replace placeholder alerts in example code above.\n",
    "    - There can be different roles for CRUD operations.  For instance, student will only interact with their own account.  Teacher may interact with many accounts.\n",
    "    - Given these CRUD operations what kind of APIs are needed?  They should map closely button/on click actions, as each action will fetch or manipulate data differently.\n",
    "\n",
    "> Extra Credit.  Student(s) could assist in rework of my Flask project from last year into a Frontend / Backend solution.  Additionally, if Frontend is done correctly it could easily be modified to work with both Spring and Flask backends.\n",
    "\n",
    "## References\n",
    "> Here are some working samples\n",
    "\n",
    "- [Fetching table data](https://nighthawkcoders.github.io/APCSP/data/database)\n",
    "\n",
    "- [Obtaining input](https://nighthawkcoders.github.io/APCSP/frontend/grades)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "JavaScript (Node.js)",
   "language": "javascript",
   "name": "javascript"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "javascript",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12 (main, Apr  5 2022, 01:53:17) \n[Clang 12.0.0 ]"
  },
  "vscode": {
   "interpreter": {
    "hash": "8b82d5009c68ba5675978267e2b13a671f2a7143d61273c5a3813c97e0b2493d"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
